### ISSUE TITLE
Swift Package

### ISSUE THREAD

**Issue by nicolaischneider** [Mattijah/QKMRZScanner#13]
Hey, thank you for your great framework! Could you add a `Package.swift` file so that it doesn't need to be installed with CocoaPods ?

**Comment by Mattijah** [comment]
Hey @nicolaischneider,

Thanks!

Adding SPM support is unfortunately a little more difficult as one of our dependencies (`SwiftyTesseract`) only supports it since `4.0.0`, but this particular version then doesn't support CocoaPods. So it's one or the other right now.

Maybe I'll try to push a different branch if I have any spare time just for SPM.

**Comment by boxidilshan** [comment]
Hi @Mattijah 

Do you have support for SPM in any other branch? Thank you.

**Comment by Mattijah** [comment]
Hey @boxidilshan, unfortunately this hasn't been done yet :( You can check however forks I think some of them do support it (don't remember now exactly which ones).

**Comment by Mattijah** [comment]
The SPM support is now available here https://github.com/Mattijah/QKMRZScanner/tree/master-spm. As mentioned previously the latest release of `SwiftyTesseract` does not support CocoaPods, so it had to be done this way unfortunately.
