### ISSUE TITLE
Swift 5 issue on SwiftTesseract.swift file

### ISSUE THREAD

**Issue by nitinfullcycle** [Mattijah/QKMRZScanner#3]
Getting below error while setup 
<img width="1181" alt="Screenshot 2019-07-24 at 11 43 50 AM" src="https://user-images.githubusercontent.com/51951209/61769596-6b056d80-ae08-11e9-94ba-28ebe51bef31.png">

Also, how it will work for USA passport?

**Comment by nitinfullcycle** [comment]
<img width="504" alt="Screenshot 2019-07-24 at 1 33 56 PM" src="https://user-images.githubusercontent.com/51951209/61791195-eda52180-ae36-11e9-9ac5-aaab5cf65c2d.png">

Can you please check this passport? it's not working

**Comment by Mattijah** [comment]
@nitinfullcycle The error is caused by one of our dependencies not the module itself. Make sure Swift version of this module (pod) is set to `Swift 4.2` and subsequently try to clean the build folder too.

<img width="1280" alt="swift_version" src="https://user-images.githubusercontent.com/3887042/61793342-39e46780-ae1f-11e9-920a-7ff941434fcd.png">

Regarding the American passport and the image posted. At the moment, the module is rather optimised for real-life documents. Passport in the image is not only tilted, but there is also too much light in the bottom-left, that's why it is difficult to scan it (*This is something I definitely plan on improving). I would recommend you to play around with real documents or different examples.

**Comment by nitinfullcycle** [comment]
First of all thank you soo much for response.
It's working with swift 4.2 but my whole project is in swift 5, so is it possible to use with swift 5?

**Comment by Mattijah** [comment]
Not at the moment. This module nor its dependencies (e.g https://github.com/SwiftyTesseract/SwiftyTesseract) has been upgraded to Swift 5 yet. If it's working for you though, just leave it at 4.2 and you can update it later. There should be no problem in that.

*I'm not sure what do you actually mean now. It should work fine. Set pods to 4.2 and leave the project at 5.

**Comment by mobileonekh** [comment]
I think the issue's title should be changed. The issue is related with Swift version not USA Passport

**Comment by nitinfullcycle** [comment]
Brother I have resolved this issue in swift 5 below is my code screenshot

<img width="594" alt="Screenshot 2019-07-25 at 9 57 41 AM" src="https://user-images.githubusercontent.com/51951209/61845915-bc723300-aec2-11e9-802b-063604410fc6.png">

Thank you soo much for help

**Comment by Mattijah** [comment]
I'm not completely sure if this was the best way how to resolve the issue (modifying code of a 3rd party library).

Do I understand it right that you weren't able to run the project with pods set to 4.2 while having the project written in Swift 5?

**Comment by nitinfullcycle** [comment]
it's working if I set pod to 4.2.

**Comment by Mattijah** [comment]
Leave it at 4.2 then. Don't modify the code. You can upgrade it to Swift 5 later when the version is available - shouldn't take too long :)
