### ISSUE TITLE
Incompatible versions of QKMRZScanner and QKMRZParser

### ISSUE THREAD

**Issue by Gorter-dev** [Mattijah/QKMRZScanner#30]
Hi!

Love your package it works amazing, but could you specify a version number for your QKMRZParser for tagged versions.
After your version bump to 3.0.0 and 2.0.0, QKMRZScanner 2.2.1 doesn't work anymore because version of QKMRZParser is updated while they aren't compatible anymore. 

This is due to the fact that in the tagged version you specify your pods using:

Pod 'QKMRZParser'

This gets the latest version of introduces compatibility issues. This could be resolved by adding:

Pod 'QKMRZParser', '1.0.0'

**Comment by Mattijah** [comment]
Hey @Gorter-dev, 

The reason why it is not working (at least if I'm not misunderstanding anything) is because in the older version there wasn't specified a concrete version for the `QKMRZParser`, so Cocoapods is fetching/using the latest one that is of course not compatible. I cannot just add what you stated as the current version in there is `2.0`. You could perhaps resolve it on your end, locally by specify to fetch `QKMRZParser` v1 before fetching the `QKMRZScanner` `2.2.1`

I would however suggest you to simply upgrading to the latest version, which is almost the same as the previous ones. If there is anything else I can do just let me know :)

**Comment by Gorter-dev** [comment]
Hey! 
I already bumped the version. So it works without a problem. I only thought it would be meaningful to update the older versions (and also newer for in the future). With a specified version, so all released versions remain working.

But if that can't be realised, then maybe a note in the readme :)

**Comment by Mattijah** [comment]
Yeah, I totally understand. Sadly, it is not possible to go back and change it 😕 Only if I amend all the following commits, which will then affect anyone who's forking these repos and I'm not aware of any other way, so it is what it is.

**Comment by Gorter-dev** [comment]
Ah got it! Sadly it is that way
